### ISSUE TITLE
Restructure repository

### ISSUE THREAD

**Issue by andrewjong** [castacks/AirStack#115]
top level

```bash
- common/
-     docker/   # top level docker, points to sub-dockers to launch everything
-     ros_ws/
-         airstack_msgs/
- ground_control_station/
-     docker/
-     ros_ws/
- robot/
-     docker/
-     ros_ws/
- simulation/
-     docker/
```
We can [chain build](https://colcon.readthedocs.io/en/released/user/using-multiple-workspaces.html#:~:text=if%20you%E2%80%99re%20unsure.-,Chaining%20workspaces,-Chaining%20workspaces%20means), build common first, then build individual workspaces.

**Comment by bradygm** [comment]
https://github.com/castacks/airstack_msgs/tree/main

**Comment by andrewjong** [comment]
Completed in #121
