### ISSUE TITLE
Random walk planner appears fails when far from origin because it doesn't understand frames

### ISSUE THREAD

**Issue by andrewjong** [castacks/AirStack#127]
discovered this issue when trying to set a different frame for VDB mapping, e.g. "world".
currently other robots fail

**Comment by tharp789** [comment]
This should be fixed now, the previous problem was that the goal points of the trajectory were being sampled around the origin and then checked if there were close enough to the robot. Now the points are sampled from around the robot and should work any pose. 
![Screenshot from 2024-11-08 15-34-34](https://github.com/user-attachments/assets/5f298c97-a1a4-41b6-acc4-fd849a8f4167)
