### ISSUE TITLE
Add README.md to random_walk package for documentation

### ISSUE THREAD

**Issue by andrewjong** [castacks/AirStack#153]
Add simple documentation describing all the parameters, how it generates a random walk, etc.

**Comment by tharp789** [comment]
Added description of random walk and parameters to the package README

**Comment by andrewjong** [comment]
Awesome!

Can we format it like we've done for [trajectory controller](https://github.com/castacks/AirStack/tree/main/robot/ros_ws/src/autonomy/3_local/c_controls/trajectory_controller#parameters)? Can format it like a table, and also add services, subscriptions, and publications. Thanks!
