### ISSUE TITLE
Which version is compatible with Ubuntu 18.04 ?

### ISSUE THREAD

**Issue by WinkySong** [castacks/AirStack#159]
which version of FASTDDS is compatible with ubuntu18.04? Also, which versions of dependencies are required (such as FASTCDR, Foonathan Memory Vendor, Asio, OpenSSL, TINYXML2 etc.) ?

**Comment by andrewjong** [comment]
Hi, I'm not sure what you're asking exactly. This project uses Docker from an Ubuntu 22.04 base image. The Dockerfiles take care of all the dependencies. The right place for support is on the Discussion page, whereas Issues are for bug or feature tracking. Thanks!
