### ISSUE TITLE
Turn drone simulation into a IssacSim Extension

### ISSUE THREAD

**Issue by smash0190** [castacks/AirStack#24]
Right now the launch script is mixed with the drone simulation. Turn drone interface in an Omniverse Extension:
https://docs.omniverse.nvidia.com/isaacsim/latest/advanced_tutorials/tutorial_extension_templates.html

**Comment by smash0190** [comment]
See pegasus extension as an example. Maybe patch or extension to pegasus?

**Comment by andrewjong** [comment]
Completed
